### ISSUE TITLE
Постинг картинок на проде не работает

### ISSUE THREAD

**Issue by Oxore** [U-Me-Chan/pissychan-front#23]
Я помержил, задеплоил, а оно не работает. Есть подозрение на версию ноды, потому что по логам ничего не понятно.

Логи (тоже уродские):
```
Error: Request failed with status code 404 at createError (/home/pm2-deploy/pissychan-v0.1.0-3f6f197-master-14.x/node_modules/axios/lib/core/createError.js:16:15) at settle (/home/pm2-deploy/pissychan-v0.1.0-3f6f197-master-14.x/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/home/pm2-deploy/pissychan-v0.1.0-3f6f197-master-14.x/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (node:events:402:35) at endReadableNT (node:internal/streams/readable:1343:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Oxore** [comment]
Да блять не закрывайся ты

**Comment by Oxore** [comment]
Вот теперь всё нормально. Дело было в опечатке названия параметра конфига `filestore_post` вместо `filestore_port` и оно работало только в девелоперском конфиге.

Закрываю.
