### ISSUE TITLE
При попытке запостить пустое сообщение с файликом .jfif ошибка как на скрине

### ISSUE THREAD

**Issue by kugimiya** [U-Me-Chan/pissychan-front#32]
![изображение](https://user-images.githubusercontent.com/8094908/158028452-759955fd-d0fb-4677-9f27-e2138b85afe4.png)

**Comment by kugimiya** [comment]
```
Error: Request failed with status code 400 at createError (/home/pm2-deploy/pissychan-v0.1.0-b7eb50d-master-14.x/node_modules/axios/lib/core/createError.js:16:15) at settle (/home/pm2-deploy/pissychan-v0.1.0-b7eb50d-master-14.x/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/home/pm2-deploy/pissychan-v0.1.0-b7eb50d-master-14.x/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (node:events:539:35) at endReadableNT (node:internal/streams/readable:1342:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Oxore** [comment]
Проблемы файлстора.

```
$ curl -vvv -F "=@sample1.jfif" http://filestore.scheoble.xyz
*   Trying 109.195.195.36:80...
* Connected to filestore.scheoble.xyz (109.195.195.36) port 80 (#0)
> POST / HTTP/1.1
> Host: filestore.scheoble.xyz
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 81187
> Content-Type: multipart/form-data; boundary=------------------------5463da47a8706c77
>
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nginx/1.20.1
< Date: Sat, 19 Mar 2022 20:57:02 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=20
< X-Powered-By: PHP/8.0.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: *
< Access-Control-Allow-Headers: *
< Cache-Control: no-cache, private
<
* Connection #0 to host filestore.scheoble.xyz left intact
{"error":"unsupported mimetype"}
```

@kugimiya, обратитесь в... А я, кстати, хуй знает куда! У начяльника @ridouchire где-то локально или скрыта репа файлстора и он её сам пилит, деплоит и никому не показывает. Так что я не знаю через какую инстанцию ему официально сообщить о проблеме. Можно ещё на писичан попробовать написать в 63-ий тред.
